server:
  port: 2262
spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=utf-8
    # url: jdbc:mysql://8.129.187.106:3306/hotel?characterEncoding=utf-8 #【阿里云的】
    username: root
    password: qbj5201314
  redis:
    host: 192.168.217.128
    database: 1     # 配置选哪个库,redis有16个库0-15，默认第一个也就是0,我自己配置1;不然一堆太乱了，还可以怎么配置？
  # 配置默认交换机可小写也可大写（小写变大写的快捷键是什么？ctrl+shfit+U）  设置数据库存入服务的字符编码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12260/eureka
      # defaultZone: http://8.129.187.106:12260/eureka  【阿里云】
  instance:
    lease-renewal-interval-in-seconds: 5  # 心跳时间
    lease-expiration-duration-in-seconds: 15       # 过期时间？
mybatis:
  type-aliases-package: com.rentHotel.item.pojo  #这里是扫描实体类；扫描mapper接口在引导类哪里写 mybatis别名扫描(不同的微服务了；只写包路劲就行？能扫描到？)