server:
  port: 2264
spring:
  application:
    name: person-service
  datasource:
    # url: jdbc:mysql://8.129.187.106:3306/hotel?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=utf-8
    username: root
    password: qbj5201314
eureka:
  client:
    service-url:
      # defaultZone: http://8.129.187.106:12260/eureka # 【】
      defaultZone: http://localhost:12260/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.renthotel.person.pojo  # 实体类