server:
  port: 2264
spring:
  application:
    name: person-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel
    username: root
    password: qbj5201314
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12260/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.renthotel.person.pojo  # 实体类