server:
  port: 12261
spring:
  application:
    name: hotel-gateway
# 添加这个在第一次访问网关的时候就不会报错
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12260/eureka
      # defaultZone: http://8.129.187.106:12260/eureka # 【阿里云的】
    registry-fetch-interval-seconds: 5  # 拉取服务的间隔时间
zuul:
  prefix: /api
  routes:        # 下面这些其实就是添加路由规则
    hotel-service: /item/**   # 路由到商品的微服务（意思是我们访问网关；就会路由到商品的页面？）
    user-service: /user/**  # 用户登录的相关数据校验的接口在这里
    auth-service: /auth/**    # 用户的基本认证，就是生成JWT、公钥私钥、token在此服务


